### ISSUE TITLE
preprocessing Problem

### ISSUE THREAD

**Issue by gebilxs** [talreiss/Accurate-Interpretable-VAD#6]
I encountered such a problem when preprocessing
```
Traceback (most recent call last):
  File "pre_processing/flows.py", line 85, in <module>
    extracting_flows(dataset_name=args.dataset_name, root=root, train=args.train)
  File "pre_processing/flows.py", line 68, in extracting_flows
    pred_flow = flownet2(ims).data
  File "/home/tjut_xuchuokun/anaconda3/envs/pytorch-CAD/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tjut_xuchuokun/Accurate-Interpretable-VAD/pre_processing/flownet_networks/flownet2_models.py", line 113, in forward
    flownetc_flow2 = self.flownetc(x)[0]
  File "/home/tjut_xuchuokun/anaconda3/envs/pytorch-CAD/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tjut_xuchuokun/Accurate-Interpretable-VAD/pre_processing/flownet_networks/FlowNetC.py", line 89, in forward
    out_corr = self.corr(out_conv3a, out_conv3b)  # False
  File "/home/tjut_xuchuokun/anaconda3/envs/pytorch-CAD/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tjut_xuchuokun/Accurate-Interpretable-VAD/pre_processing/flownet_networks/correlation_package/correlation.py", line 58, in forward
    result = CorrelationFunction.apply(input1, input2, self.pad_size, self.kernel_size, self.max_displacement, self.stride1, self.stride2, self.corr_multiply)
  File "/home/tjut_xuchuokun/Accurate-Interpretable-VAD/pre_processing/flownet_networks/correlation_package/correlation.py", line 24, in forward
    correlation_cuda.forward(input1, input2, rbot1, rbot2, output,
AttributeError: module 'correlation_cuda' has no attribute 'forward'
```

I think I have followed the Readme to build the lib file

**Comment by gebilxs** [comment]
pip uninstall wrong package
